### ISSUE TITLE
dependency vulnerabilities?

### ISSUE THREAD

**Issue by tehpsalmist** [chiefGui/superstate#20]
Hey! Love the library! I might even try to use this at work, if possible. One thing I noticed when I started installing to try it out is that the dependencies have a bunch of vulnerabilites. Do you have a plan to upgrade those soon?

Thanks again for putting this out to the world. The "draft" concept looks super useful!

**Comment by chiefGui** [comment]
Hey @tehpsalmist!

I think the dependencies with vulnerabilities are related to the [dependencies of the monorepo](https://github.com/chiefGui/superstate/blob/main/package.json) and mean no harm to the users of superstate and its three packages (`core`, `react` and `adapters`), especially because the only dependencies they have are `react` and `fast-deep-equal`.

I mean, did your package manager tell you something at the moment you tried installing one of them?

Either way, I'm taking some time now to repair those on the repo itself. Thank you so much for bringing it up!

**Comment by chiefGui** [comment]
I think the vulnerabilities should be gone by now. Can you confirm that, @tehpsalmist?

**Comment by tehpsalmist** [comment]
Yarn audit still yields 15 vulnerabilities. I wonder if yarn 2 would resolve them. I understand that this isn't mission critical to the software, but it can instill confidence in would-be users when they pull it the first time, since I would think folks will want to make suggestions and PRs to this repo given how new it is. I really love the concept. Still messing around with the API to figure out how to make best use of it.

**Comment by tehpsalmist** [comment]
To be clear, I'm getting 0 vulnerabilities in my example project where I install it via npm. But local dev on this repo is where I'm still seeing the vulnerabilities.

**Comment by chiefGui** [comment]
Thank you for your response, @tehpsalmist.

> Yarn audit still yields 15 vulnerabilities.

I think you're auditing against the monorepo itself instead of the packages (`@superstate/core`, `@superstate/react`, etc...), right? Because then you're right&mdash;superstate itself is safe from vulnerabilities, however the monorepo and its dependencies, mostly from docusaurus and nx, can be compromised.

I will take a look - thank you for bringing this up again and hope you enjoy your time with superstate. :)
